/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about the operations available in this version.
type SimpleLink struct {
	Id string `json:"id,omitempty"`
	StyleClass string `json:"styleClass,omitempty"`
	IconClass string `json:"iconClass,omitempty"`
	Label string `json:"label,omitempty"`
	Title string `json:"title,omitempty"`
	Href string `json:"href,omitempty"`
	Weight int32 `json:"weight,omitempty"`
}
