/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A webhook.
type Webhook struct {
	// The ID of the webhook.
	Id int64 `json:"id"`
	// The JQL filter that specifies which issues the webhook is sent for.
	JqlFilter string `json:"jqlFilter"`
	// A list of field IDs. When the issue changelog contains any of the fields, the webhook `jira:issue_updated` is sent. If this parameter is not present, the app is notified about all field updates.
	FieldIdsFilter []string `json:"fieldIdsFilter,omitempty"`
	// A list of issue property keys. A change of those issue properties triggers the `issue_property_set` or `issue_property_deleted` webhooks. If this parameter is not present, the app is notified about all issue property updates.
	IssuePropertyKeysFilter []string `json:"issuePropertyKeysFilter,omitempty"`
	// The Jira events that trigger the webhook.
	Events []string `json:"events"`
	ExpirationDate int64 `json:"expirationDate,omitempty"`
}
