/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnrestrictedUserEmail struct {
	// The accountId of the user
	AccountId string `json:"accountId,omitempty"`
	// The email of the user
	Email string `json:"email,omitempty"`
}
