/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about a notification associated with an event.
type EventNotification struct {
	// Expand options that include additional event notification details in the response.
	Expand string `json:"expand,omitempty"`
	// The ID of the notification.
	Id int64 `json:"id,omitempty"`
	// Identifies the recipients of the notification.
	NotificationType string `json:"notificationType,omitempty"`
	// The value of the `notificationType`:   *  `User` The `parameter` is the user account ID.  *  `Group` The `parameter` is the group name.  *  `ProjectRole` The `parameter` is the project role ID.  *  `UserCustomField` The `parameter` is the ID of the custom field.  *  `GroupCustomField` The `parameter` is the ID of the custom field.
	Parameter string `json:"parameter,omitempty"`
	// The specified group.
	Group *AllOfEventNotificationGroup `json:"group,omitempty"`
	// The custom user or group field.
	Field *AllOfEventNotificationField `json:"field,omitempty"`
	// The email address.
	EmailAddress string `json:"emailAddress,omitempty"`
	// The specified project role.
	ProjectRole *AllOfEventNotificationProjectRole `json:"projectRole,omitempty"`
	// The specified user.
	User *AllOfEventNotificationUser `json:"user,omitempty"`
}
