/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A workflow with transition rules.
type WorkflowTransitionRules struct {
	WorkflowId *WorkflowId `json:"workflowId"`
	// The list of post functions within the workflow.
	PostFunctions []ConnectWorkflowTransitionRule `json:"postFunctions"`
	// The list of conditions within the workflow.
	Conditions []ConnectWorkflowTransitionRule `json:"conditions"`
	// The list of validators within the workflow.
	Validators []ConnectWorkflowTransitionRule `json:"validators"`
}
