/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActorsMap struct {
	// The user account ID of the user to add.
	User []string `json:"user,omitempty"`
	// The name of the group to add.
	Group []string `json:"group,omitempty"`
}
