/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// List of custom fields using the version.
type VersionUsageInCustomField struct {
	// The name of the custom field.
	FieldName string `json:"fieldName,omitempty"`
	// The ID of the custom field.
	CustomFieldId int64 `json:"customFieldId,omitempty"`
	// Count of the issues where the custom field contains the version.
	IssueCountWithVersionInCustomField int64 `json:"issueCountWithVersionInCustomField,omitempty"`
}
