/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of a dashboard.
type DashboardDetails struct {
	// The name of the dashboard.
	Name string `json:"name"`
	// The description of the dashboard.
	Description string `json:"description,omitempty"`
	// The share permissions for the dashboard.
	SharePermissions []SharePermission `json:"sharePermissions"`
	// The edit permissions for the dashboard.
	EditPermissions []SharePermission `json:"editPermissions"`
}
