/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of the contextual configuration for a custom field.
type ContextualConfiguration struct {
	// The ID of the context the configuration is associated with.
	ContextId int64 `json:"contextId"`
	// The configuration associated with the context.
	Configuration *Object `json:"configuration,omitempty"`
	// The schema associated with the context.
	Schema *Object `json:"schema,omitempty"`
}
