/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of webhooks to register.
type WebhookRegistrationDetails struct {
	// A list of webhooks.
	Webhooks []WebhookDetails `json:"webhooks"`
	// The URL that specifies where to send the webhooks. This URL must use the same base URL as the Connect app.
	Url string `json:"url"`
}
