/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Property key details.
type PropertyKey struct {
	// The URL of the property.
	Self string `json:"self,omitempty"`
	// The key of the property.
	Key string `json:"key,omitempty"`
}
