/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about a project role.
type ProjectRoleDetails struct {
	// The URL the project role details.
	Self string `json:"self,omitempty"`
	// The name of the project role.
	Name string `json:"name,omitempty"`
	// The ID of the project role.
	Id int64 `json:"id,omitempty"`
	// The description of the project role.
	Description string `json:"description,omitempty"`
	// Whether this role is the admin role for the project.
	Admin bool `json:"admin,omitempty"`
	// The scope of the role. Indicated for roles associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO).
	Scope *AllOfProjectRoleDetailsScope `json:"scope,omitempty"`
	// Whether the roles are configurable for this project.
	RoleConfigurable bool `json:"roleConfigurable,omitempty"`
	// The translated name of the project role.
	TranslatedName string `json:"translatedName,omitempty"`
	// Whether this role is the default role for the project.
	Default_ bool `json:"default,omitempty"`
}
