/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type JsonNode struct {
	Elements *interface{} `json:"elements,omitempty"`
	Pojo bool `json:"pojo,omitempty"`
	ContainerNode bool `json:"containerNode,omitempty"`
	MissingNode bool `json:"missingNode,omitempty"`
	Object bool `json:"object,omitempty"`
	ValueNode bool `json:"valueNode,omitempty"`
	Number bool `json:"number,omitempty"`
	IntegralNumber bool `json:"integralNumber,omitempty"`
	FloatingPointNumber bool `json:"floatingPointNumber,omitempty"`
	Int_ bool `json:"int,omitempty"`
	Long bool `json:"long,omitempty"`
	Double bool `json:"double,omitempty"`
	BigDecimal bool `json:"bigDecimal,omitempty"`
	BigInteger bool `json:"bigInteger,omitempty"`
	Textual bool `json:"textual,omitempty"`
	Boolean bool `json:"boolean,omitempty"`
	Binary bool `json:"binary,omitempty"`
	NumberValue float64 `json:"numberValue,omitempty"`
	NumberType string `json:"numberType,omitempty"`
	IntValue int32 `json:"intValue,omitempty"`
	LongValue int64 `json:"longValue,omitempty"`
	BigIntegerValue int32 `json:"bigIntegerValue,omitempty"`
	DoubleValue float64 `json:"doubleValue,omitempty"`
	DecimalValue float64 `json:"decimalValue,omitempty"`
	BooleanValue bool `json:"booleanValue,omitempty"`
	BinaryValue []string `json:"binaryValue,omitempty"`
	ValueAsInt int32 `json:"valueAsInt,omitempty"`
	ValueAsLong int64 `json:"valueAsLong,omitempty"`
	ValueAsDouble float64 `json:"valueAsDouble,omitempty"`
	ValueAsBoolean bool `json:"valueAsBoolean,omitempty"`
	TextValue string `json:"textValue,omitempty"`
	ValueAsText string `json:"valueAsText,omitempty"`
	FieldNames *interface{} `json:"fieldNames,omitempty"`
	Array bool `json:"array,omitempty"`
	Fields *interface{} `json:"fields,omitempty"`
	Null bool `json:"null,omitempty"`
}
