/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about a notification scheme.
type NotificationScheme struct {
	// Expand options that include additional notification scheme details in the response.
	Expand string `json:"expand,omitempty"`
	// The ID of the notification scheme.
	Id int64 `json:"id,omitempty"`
	Self string `json:"self,omitempty"`
	// The name of the notification scheme.
	Name string `json:"name,omitempty"`
	// The description of the notification scheme.
	Description string `json:"description,omitempty"`
	// The notification events and associated recipients.
	NotificationSchemeEvents []NotificationSchemeEvent `json:"notificationSchemeEvents,omitempty"`
	// The scope of the notification scheme.
	Scope *AllOfNotificationSchemeScope `json:"scope,omitempty"`
}
