/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The list of users found in a search, including header text (Showing X of Y matching users) and total of matched users.
type FoundUsers struct {
	Users []UserPickerUser `json:"users,omitempty"`
	// The total number of users found in the search.
	Total int32 `json:"total,omitempty"`
	// Header text indicating the number of users in the response and the total number of users found in the search.
	Header string `json:"header,omitempty"`
}
