/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of global permissions to look up and project permissions with associated projects and issues to look up.
type BulkPermissionsRequestBean struct {
	// Project permissions with associated projects and issues to look up.
	ProjectPermissions []BulkProjectPermissions `json:"projectPermissions,omitempty"`
	// Global permissions to look up.
	GlobalPermissions []string `json:"globalPermissions,omitempty"`
	// The account ID of a user.
	AccountId string `json:"accountId,omitempty"`
}
