/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about a task.
type TaskProgressBeanObject struct {
	// The URL of the task.
	Self string `json:"self"`
	// The ID of the task.
	Id string `json:"id"`
	// The description of the task.
	Description string `json:"description,omitempty"`
	// The status of the task.
	Status string `json:"status"`
	// Information about the progress of the task.
	Message string `json:"message,omitempty"`
	// The result of the task execution.
	Result *Object `json:"result,omitempty"`
	// The ID of the user who submitted the task.
	SubmittedBy int64 `json:"submittedBy"`
	// The progress of the task, as a percentage complete.
	Progress int64 `json:"progress"`
	// The execution time of the task, in milliseconds.
	ElapsedRuntime int64 `json:"elapsedRuntime"`
	// A timestamp recording when the task was submitted.
	Submitted int64 `json:"submitted"`
	// A timestamp recording when the task was started.
	Started int64 `json:"started,omitempty"`
	// A timestamp recording when the task was finished.
	Finished int64 `json:"finished,omitempty"`
	// A timestamp recording when the task progress was last updated.
	LastUpdate int64 `json:"lastUpdate"`
}
