/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// List of users and groups found in a search.
type FoundUsersAndGroups struct {
	Users *FoundUsers `json:"users,omitempty"`
	Groups *FoundGroups `json:"groups,omitempty"`
}
