/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A collection of transition rules.
type WorkflowRules struct {
	// The workflow conditions. ([Deprecated](https://community.developer.atlassian.com/t/deprecation-of-conditions-body-param/48884))
	Conditions []WorkflowTransitionRule `json:"conditions,omitempty"`
	ConditionsTree *WorkflowCondition `json:"conditionsTree,omitempty"`
	// The workflow validators.
	Validators []WorkflowTransitionRule `json:"validators,omitempty"`
	// The workflow post functions.
	PostFunctions []WorkflowTransitionRule `json:"postFunctions,omitempty"`
}
