/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of a field.
type Field struct {
	// The ID of the field.
	Id string `json:"id"`
	// The name of the field.
	Name string `json:"name"`
	Schema *JsonTypeBean `json:"schema"`
	// The description of the field.
	Description string `json:"description,omitempty"`
	// The key of the field.
	Key string `json:"key,omitempty"`
	// Whether the field is locked.
	IsLocked bool `json:"isLocked,omitempty"`
	// Whether the field is shown on screen or not.
	IsUnscreenable bool `json:"isUnscreenable,omitempty"`
	// The searcher key of the field. Returned for custom fields.
	SearcherKey string `json:"searcherKey,omitempty"`
	// Number of screens where the field is used.
	ScreensCount int64 `json:"screensCount,omitempty"`
	// Number of contexts where the field is used.
	ContextsCount int64 `json:"contextsCount,omitempty"`
	LastUsed *FieldLastUsed `json:"lastUsed,omitempty"`
}
