/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of a user, group, field, or project role that holds a permission. See [Holder object](../api-group-permission-schemes/#holder-object) in *Get all permission schemes* for more information.
type PermissionHolder struct {
	// The type of permission holder.
	Type_ string `json:"type"`
	// The identifier of permission holder.
	Parameter string `json:"parameter,omitempty"`
	// Expand options that include additional permission holder details in the response.
	Expand string `json:"expand,omitempty"`
}
