/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of a workflow transition.
type Transition struct {
	// The ID of the transition.
	Id string `json:"id"`
	// The name of the transition.
	Name string `json:"name"`
	// The description of the transition.
	Description string `json:"description"`
	// The statuses the transition can start from.
	From []string `json:"from"`
	// The status the transition goes to.
	To string `json:"to"`
	// The type of the transition.
	Type_ string `json:"type"`
	Screen *TransitionScreenDetails `json:"screen,omitempty"`
	Rules *WorkflowRules `json:"rules,omitempty"`
	// The properties of the transition.
	Properties map[string]Object `json:"properties,omitempty"`
}
