/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of a dashboard.
type Dashboard struct {
	Description string `json:"description,omitempty"`
	// The ID of the dashboard.
	Id string `json:"id,omitempty"`
	// Whether the dashboard is selected as a favorite by the user.
	IsFavourite bool `json:"isFavourite,omitempty"`
	// The name of the dashboard.
	Name string `json:"name,omitempty"`
	// The owner of the dashboard.
	Owner *AllOfDashboardOwner `json:"owner,omitempty"`
	// The number of users who have this dashboard as a favorite.
	Popularity int64 `json:"popularity,omitempty"`
	// The rank of this dashboard.
	Rank int32 `json:"rank,omitempty"`
	// The URL of these dashboard details.
	Self string `json:"self,omitempty"`
	// The details of any view share permissions for the dashboard.
	SharePermissions []SharePermission `json:"sharePermissions,omitempty"`
	// The details of any edit share permissions for the dashboard.
	EditPermissions []SharePermission `json:"editPermissions,omitempty"`
	// The URL of the dashboard.
	View string `json:"view,omitempty"`
	// Whether the current user has permission to edit the dashboard.
	IsWritable bool `json:"isWritable,omitempty"`
}
