/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about a project.
type ProjectDetails struct {
	// The URL of the project details.
	Self string `json:"self,omitempty"`
	// The ID of the project.
	Id string `json:"id,omitempty"`
	// The key of the project.
	Key string `json:"key,omitempty"`
	// The name of the project.
	Name string `json:"name,omitempty"`
	// The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project.
	ProjectTypeKey string `json:"projectTypeKey,omitempty"`
	// Whether or not the project is simplified.
	Simplified bool `json:"simplified,omitempty"`
	// The URLs of the project's avatars.
	AvatarUrls *AllOfProjectDetailsAvatarUrls `json:"avatarUrls,omitempty"`
	// The category the project belongs to.
	ProjectCategory *AllOfProjectDetailsProjectCategory `json:"projectCategory,omitempty"`
}
