/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Details about a project.
type Project struct {
	// Expand options that include additional project details in the response.
	Expand string `json:"expand,omitempty"`
	// The URL of the project details.
	Self string `json:"self,omitempty"`
	// The ID of the project.
	Id string `json:"id,omitempty"`
	// The key of the project.
	Key string `json:"key,omitempty"`
	// A brief description of the project.
	Description string `json:"description,omitempty"`
	// The username of the project lead.
	Lead *AllOfProjectLead `json:"lead,omitempty"`
	// List of the components contained in the project.
	Components []ProjectComponent `json:"components,omitempty"`
	// List of the issue types available in the project.
	IssueTypes []IssueTypeDetails `json:"issueTypes,omitempty"`
	// A link to information about this project, such as project documentation.
	Url string `json:"url,omitempty"`
	// An email address associated with the project.
	Email string `json:"email,omitempty"`
	// The default assignee when creating issues for this project.
	AssigneeType string `json:"assigneeType,omitempty"`
	// The versions defined in the project. For more information, see [Create version](#api-rest-api-3-version-post).
	Versions []Version `json:"versions,omitempty"`
	// The name of the project.
	Name string `json:"name,omitempty"`
	// The name and self URL for each role defined in the project. For more information, see [Create project role](#api-rest-api-3-role-post).
	Roles map[string]string `json:"roles,omitempty"`
	// The URLs of the project's avatars.
	AvatarUrls *AllOfProjectAvatarUrls `json:"avatarUrls,omitempty"`
	// The category the project belongs to.
	ProjectCategory *AllOfProjectProjectCategory `json:"projectCategory,omitempty"`
	// The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project.
	ProjectTypeKey string `json:"projectTypeKey,omitempty"`
	// Whether the project is simplified.
	Simplified bool `json:"simplified,omitempty"`
	// The type of the project.
	Style string `json:"style,omitempty"`
	// Whether the project is selected as a favorite.
	Favourite bool `json:"favourite,omitempty"`
	// Whether the project is private.
	IsPrivate bool `json:"isPrivate,omitempty"`
	// The issue type hierarchy for the project.
	IssueTypeHierarchy *AllOfProjectIssueTypeHierarchy `json:"issueTypeHierarchy,omitempty"`
	// User permissions on the project
	Permissions *AllOfProjectPermissions `json:"permissions,omitempty"`
	// Map of project properties
	Properties map[string]Object `json:"properties,omitempty"`
	// Unique ID for next-gen projects.
	Uuid string `json:"uuid,omitempty"`
	// Insights about the project.
	Insight *AllOfProjectInsight `json:"insight,omitempty"`
	// Whether the project is marked as deleted.
	Deleted bool `json:"deleted,omitempty"`
	// The date when the project is deleted permanently.
	RetentionTillDate time.Time `json:"retentionTillDate,omitempty"`
	// The date when the project was marked as deleted.
	DeletedDate time.Time `json:"deletedDate,omitempty"`
	// The user who marked the project as deleted.
	DeletedBy *AllOfProjectDeletedBy `json:"deletedBy,omitempty"`
	// Whether the project is archived.
	Archived bool `json:"archived,omitempty"`
	// The date when the project was archived.
	ArchivedDate time.Time `json:"archivedDate,omitempty"`
	// The user who archived the project.
	ArchivedBy *AllOfProjectArchivedBy `json:"archivedBy,omitempty"`
	// The project landing page info.
	LandingPageInfo *AllOfProjectLandingPageInfo `json:"landingPageInfo,omitempty"`
}
