/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of a link between issues.
type IssueLink struct {
	// The ID of the issue link.
	Id string `json:"id,omitempty"`
	// The URL of the issue link.
	Self string `json:"self,omitempty"`
	// The type of link between the issues.
	Type_ *AllOfIssueLinkType_ `json:"type"`
	// The issue the link joins to.
	InwardIssue *AllOfIssueLinkInwardIssue `json:"inwardIssue"`
	// The issue the link originates from.
	OutwardIssue *AllOfIssueLinkOutwardIssue `json:"outwardIssue"`
}
