/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The group that the filter is shared with. For a request, specify the `name` property for the group.
type AllOfSharePermissionGroup struct {
	// The name of group.
	Name string `json:"name,omitempty"`
	// The URL for these group details.
	Self string `json:"self,omitempty"`
}
